import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export async function exportDailyPDF(
  day: number,
  score: number,
  ibadat: Record<string, boolean>
) {
  const rows = Object.entries(ibadat)
    .map(
      ([key, val]) =>
        `<tr><td>${key}</td><td>${val ? "✅" : "❌"}</td></tr>`
    )
    .join("");

  const html = `
    <html>
      <body style="font-family: Arial; padding: 24px;">
        <h2>Ramadan Day ${day} Report 🌙</h2>
        <p><strong>Score:</strong> ${score} / 100</p>
        <table border="1" cellpadding="8" cellspacing="0">
          <tr><th>Ibadat</th><th>Status</th></tr>
          ${rows}
        </table>
        <p style="margin-top:20px;">Generated by Ramadan Tracker</p>
      </body>
    </html>
  `;

  const file = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(file.uri);
}
